import type { Timestamp } from "firebase/firestore";

export const PROFILE_USER_TYPES = ["company", "professional", "individual"] as const;

export type ProfileUserType = (typeof PROFILE_USER_TYPES)[number];
export type ProfileStatus = "active" | "inactive";

export type UserProfileRecord = {
  id: string;
  userId: string;
  tenantId: string;
  profileType: ProfileUserType;
  userType: ProfileUserType;
  fullName: string;
  email: string;
  phone: string;
  phoneE164: string;
  companyName: string;
  companyPosition: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  profilePhotoUrl: string | null;
  highestDegreeHeld: string;
  fieldOfStudy: string;
  yearsOfExperience: string;
  currentRole: string;
  bio: string;
  skills: string[];
  linkedinUrl: string;
  instagramHandle: string;
  youtubeChannel: string;
  websiteUrl: string;
  professionalHeadline: string;
  expertiseAreas: string[];
  certifications: string[];
  coachingExperienceYears: string;
  trainingExperienceYears: string;
  industryFocus: string;
  languagesSpoken: string[];
  coachExperienceSummary: string;
  coachPrimaryIndustry: string;
  coachIndustryExperience: string;
  coachExpertiseAreas: string[];
  coachCoachingAreas: string[];
  coachMethods: string[];
  coachTargetAudience: string[];
  coachSessionFormats: string[];
  coachServicesOther: string;
  coachCredentials: string[];
  coachOutcomeFocus: string;
  coachAvailability: string;
  individualPortalPurpose: string;
  individualExperienceLevel: string;
  individualExpertiseLevel: string;
  individualDevelopmentAreas: string[];
  individualLearningPreferences: string[];
  individualTargetAudience: string[];
  individualGoals: string;
  individualTimeCommitment: string;
  individualPreferredSessionFormat: string;
  individualTargetOutcomes: string[];
  individualCurrentChallenges: string;
  publicProfileReady: boolean;
  companyLegalName: string;
  companyDisplayName: string;
  companyType: string;
  companyLogoUrl: string | null;
  companyDescription: string;
  industry: string;
  employeeCountRange: string;
  primaryContactName: string;
  mandatoryProfileCompleted: boolean;
  profileCompletionPercent: number;
  profileCompletionRewardStatus?: "credited" | "already-credited" | "skipped";
  assignmentEligible: boolean;
  status: ProfileStatus;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
};

export type UserProfileSaveInput = {
  profileId?: string;
  userId: string;
  tenantId: string;
  userType: ProfileUserType;
  fullName: string;
  email: string;
  phoneE164: string;
  companyName?: string;
  companyPosition?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  country?: string;
  postalCode?: string;
  profilePhotoUrl?: string | null;
  highestDegreeHeld?: string;
  fieldOfStudy?: string;
  yearsOfExperience?: string;
  currentRole?: string;
  bio?: string;
  skills?: string[];
  linkedinUrl?: string;
  instagramHandle?: string;
  youtubeChannel?: string;
  websiteUrl?: string;
  professionalHeadline?: string;
  expertiseAreas?: string[];
  certifications?: string[];
  coachingExperienceYears?: string;
  trainingExperienceYears?: string;
  industryFocus?: string;
  languagesSpoken?: string[];
  coachExperienceSummary?: string;
  coachPrimaryIndustry?: string;
  coachIndustryExperience?: string;
  coachExpertiseAreas?: string[];
  coachCoachingAreas?: string[];
  coachMethods?: string[];
  coachTargetAudience?: string[];
  coachSessionFormats?: string[];
  coachServicesOther?: string;
  coachCredentials?: string[];
  coachOutcomeFocus?: string;
  coachAvailability?: string;
  individualPortalPurpose?: string;
  individualExperienceLevel?: string;
  individualExpertiseLevel?: string;
  individualDevelopmentAreas?: string[];
  individualLearningPreferences?: string[];
  individualTargetAudience?: string[];
  individualGoals?: string;
  individualTimeCommitment?: string;
  individualPreferredSessionFormat?: string;
  individualTargetOutcomes?: string[];
  individualCurrentChallenges?: string;
  publicProfileReady?: boolean;
  companyLegalName?: string;
  companyDisplayName?: string;
  companyType?: string;
  companyLogoUrl?: string | null;
  companyDescription?: string;
  industry?: string;
  employeeCountRange?: string;
  primaryContactName?: string;
  status?: ProfileStatus;
};

export type UserProfileFormValues = {
  fullName: string;
  userType: ProfileUserType;
  email: string;
  phoneE164: string;
  profilePhotoUrl: string;
  companyName: string;
  companyPosition: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  highestDegreeHeld: string;
  fieldOfStudy: string;
  yearsOfExperience: string;
  currentRole: string;
  bio: string;
  linkedinUrl: string;
  instagramHandle: string;
  youtubeChannel: string;
  websiteUrl: string;
  professionalHeadline: string;
  expertiseAreas: string;
  certifications: string;
  coachingExperienceYears: string;
  trainingExperienceYears: string;
  industryFocus: string;
  languagesSpoken: string;
  coachExperienceSummary: string;
  coachPrimaryIndustry: string;
  coachIndustryExperience: string;
  coachExpertiseAreas: string;
  coachCoachingAreas: string;
  coachMethods: string;
  coachTargetAudience: string;
  coachSessionFormats: string;
  coachServicesOther: string;
  coachCredentials: string;
  coachOutcomeFocus: string;
  coachAvailability: string;
  individualPortalPurpose: string;
  individualExperienceLevel: string;
  individualExpertiseLevel: string;
  individualDevelopmentAreas: string;
  individualLearningPreferences: string;
  individualTargetAudience: string;
  individualGoals: string;
  individualTimeCommitment: string;
  individualPreferredSessionFormat: string;
  individualTargetOutcomes: string;
  individualCurrentChallenges: string;
  companyLegalName: string;
  companyDisplayName: string;
  companyType: string;
  companyDescription: string;
  industry: string;
  employeeCountRange: string;
  primaryContactName: string;
};

export const DEFAULT_PROFILE_FORM_VALUES: UserProfileFormValues = {
  fullName: "",
  userType: "individual",
  email: "",
  phoneE164: "",
  profilePhotoUrl: "",
  companyName: "",
  companyPosition: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  country: "",
  postalCode: "",
  highestDegreeHeld: "",
  fieldOfStudy: "",
  yearsOfExperience: "",
  currentRole: "",
  bio: "",
  linkedinUrl: "",
  instagramHandle: "",
  youtubeChannel: "",
  websiteUrl: "",
  professionalHeadline: "",
  expertiseAreas: "",
  certifications: "",
  coachingExperienceYears: "",
  trainingExperienceYears: "",
  industryFocus: "",
  languagesSpoken: "",
  coachExperienceSummary: "",
  coachPrimaryIndustry: "",
  coachIndustryExperience: "",
  coachExpertiseAreas: "",
  coachCoachingAreas: "",
  coachMethods: "",
  coachTargetAudience: "",
  coachSessionFormats: "",
  coachServicesOther: "",
  coachCredentials: "",
  coachOutcomeFocus: "",
  coachAvailability: "",
  individualPortalPurpose: "",
  individualExperienceLevel: "",
  individualExpertiseLevel: "",
  individualDevelopmentAreas: "",
  individualLearningPreferences: "",
  individualTargetAudience: "",
  individualGoals: "",
  individualTimeCommitment: "",
  individualPreferredSessionFormat: "",
  individualTargetOutcomes: "",
  individualCurrentChallenges: "",
  companyLegalName: "",
  companyDisplayName: "",
  companyType: "",
  companyDescription: "",
  industry: "",
  employeeCountRange: "",
  primaryContactName: "",
};